"""add cooldowns table

Revision ID: 0f912c7fb83e
Revises: f9f30e009c4f
Create Date: 2026-08-09 06:01:53.627868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f912c7fb83e'
down_revision: Union[str, None] = 'f9f30e009c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooldowns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('until_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooldowns_key'), 'cooldowns', ['key'], unique=False)
    op.create_index(op.f('ix_cooldowns_scope'), 'cooldowns', ['scope'], unique=False)
    op.create_index(op.f('ix_cooldowns_until_ts'), 'cooldowns', ['until_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cooldowns_until_ts'), table_name='cooldowns')
    op.drop_index(op.f('ix_cooldowns_scope'), table_name='cooldowns')
    op.drop_index(op.f('ix_cooldowns_key'), table_name='cooldowns')
    op.drop_table('cooldowns')
    # ### end Alembic commands ###
