"""add developing_setups table

Revision ID: 3420091b3f44
Revises: 0f912c7fb83e
Create Date: 2026-08-09 06:27:09.251567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3420091b3f44'
down_revision: Union[str, None] = '0f912c7fb83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developing_setups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('missing_conditions', sa.JSON(), nullable=False),
    sa.Column('projections', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developing_setups_strategy_version'), 'developing_setups', ['strategy_version'], unique=False)
    op.create_index(op.f('ix_developing_setups_symbol'), 'developing_setups', ['symbol'], unique=False)
    op.create_index(op.f('ix_developing_setups_ts'), 'developing_setups', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_developing_setups_ts'), table_name='developing_setups')
    op.drop_index(op.f('ix_developing_setups_symbol'), table_name='developing_setups')
    op.drop_index(op.f('ix_developing_setups_strategy_version'), table_name='developing_setups')
    op.drop_table('developing_setups')
    # ### end Alembic commands ###
