"""add protection_events table

Revision ID: dceb7a084c56
Revises: fed352b9573a
Create Date: 2026-08-09 05:42:09.310636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dceb7a084c56'
down_revision: Union[str, None] = 'fed352b9573a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protection_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('t_protection_ms', sa.Float(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protection_events_measured_at'), 'protection_events', ['measured_at'], unique=False)
    op.create_index(op.f('ix_protection_events_symbol'), 'protection_events', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_protection_events_symbol'), table_name='protection_events')
    op.drop_index(op.f('ix_protection_events_measured_at'), table_name='protection_events')
    op.drop_table('protection_events')
    # ### end Alembic commands ###
