"""add symbol_universe table

Revision ID: f9f30e009c4f
Revises: dceb7a084c56
Create Date: 2026-08-09 05:50:32.279485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f30e009c4f'
down_revision: Union[str, None] = 'dceb7a084c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol_universe',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('filters_passed', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_symbol_universe_updated_at'), 'symbol_universe', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbol_universe_updated_at'), table_name='symbol_universe')
    op.drop_table('symbol_universe')
    # ### end Alembic commands ###
