"""initial schema

Revision ID: fed352b9573a
Revises: 
Create Date: 2026-08-09 05:13:23.728930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed352b9573a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('fill_time', sa.DateTime(), nullable=True),
    sa.Column('markout_5s_bps', sa.Float(), nullable=True),
    sa.Column('markout_30s_bps', sa.Float(), nullable=True),
    sa.Column('markout_5s_r', sa.Float(), nullable=True),
    sa.Column('markout_30s_r', sa.Float(), nullable=True),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_attempts_attempted_at'), 'entry_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_entry_attempts_config_hash'), 'entry_attempts', ['config_hash'], unique=False)
    op.create_index(op.f('ix_entry_attempts_outcome'), 'entry_attempts', ['outcome'], unique=False)
    op.create_index(op.f('ix_entry_attempts_symbol'), 'entry_attempts', ['symbol'], unique=False)
    op.create_table('kill_switch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('killed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('set_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rejections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rejections_config_hash'), 'rejections', ['config_hash'], unique=False)
    op.create_index(op.f('ix_rejections_evaluated_at'), 'rejections', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_rejections_reason'), 'rejections', ['reason'], unique=False)
    op.create_index(op.f('ix_rejections_symbol'), 'rejections', ['symbol'], unique=False)
    op.create_table('self_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_self_checks_checked_at'), 'self_checks', ['checked_at'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.String(), nullable=False),
    sa.Column('signal_time', sa.DateTime(), nullable=False),
    sa.Column('entry_reference', sa.Float(), nullable=False),
    sa.Column('stop', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('preset_id', sa.String(), nullable=True),
    sa.Column('preset_version', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('regime', sa.String(), nullable=True),
    sa.Column('session', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_config_hash'), 'signals', ['config_hash'], unique=False)
    op.create_index(op.f('ix_signals_signal_time'), 'signals', ['signal_time'], unique=False)
    op.create_index(op.f('ix_signals_strategy_version'), 'signals', ['strategy_version'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.Column('exit_reason', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('preset_id', sa.String(), nullable=True),
    sa.Column('preset_version', sa.Integer(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('mfe', sa.Float(), nullable=True),
    sa.Column('score_at_exit', sa.Float(), nullable=True),
    sa.Column('cost_breakdown', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_config_hash'), 'trades', ['config_hash'], unique=False)
    op.create_index(op.f('ix_trades_opened_at'), 'trades', ['opened_at'], unique=False)
    op.create_index(op.f('ix_trades_strategy_version'), 'trades', ['strategy_version'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_trade_id'), 'trades', ['trade_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trade_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_version'), table_name='trades')
    op.drop_index(op.f('ix_trades_opened_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_config_hash'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_strategy_version'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_time'), table_name='signals')
    op.drop_index(op.f('ix_signals_config_hash'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_self_checks_checked_at'), table_name='self_checks')
    op.drop_table('self_checks')
    op.drop_index(op.f('ix_rejections_symbol'), table_name='rejections')
    op.drop_index(op.f('ix_rejections_reason'), table_name='rejections')
    op.drop_index(op.f('ix_rejections_evaluated_at'), table_name='rejections')
    op.drop_index(op.f('ix_rejections_config_hash'), table_name='rejections')
    op.drop_table('rejections')
    op.drop_table('kill_switch')
    op.drop_index(op.f('ix_entry_attempts_symbol'), table_name='entry_attempts')
    op.drop_index(op.f('ix_entry_attempts_outcome'), table_name='entry_attempts')
    op.drop_index(op.f('ix_entry_attempts_config_hash'), table_name='entry_attempts')
    op.drop_index(op.f('ix_entry_attempts_attempted_at'), table_name='entry_attempts')
    op.drop_table('entry_attempts')
    # ### end Alembic commands ###
